# dataset
data_path: "./data"
filename: "wtbdata_245days.csv"
input_len: 288
output_len: 288
var_len: 12
var_out: 1
capacity: 134

model_name: 'GruAttModel'
# optionnal: [ Transformer, GruAttModel]
train_days: 200
val_days: 45
test_days: 0
total_days: 245
real_value: False

num_workers: 2
epoch: 10 
patient: 3
batch_size: 16
output_path: "./output/baseline"
model_path: "output/baseline/20220705175536/"
log_per_steps: 100
lr: 0.001

# Model
model:
    hidden_dims: 64
    nhead: 4
    dropout: 0.2
    num_layers: 2

loss:
    name: "FilterMSELoss"