
#creat time 2022-06-09 14:43.
#Author : gouzhumei.
#
#:param: base: including the seed, which means the random seed of initial setting, and debug
#:param: data: static is the static features, train_len and test_len is the length of train and test parts u used,label_index is the label' location
#:param: train: optim is used to chose your optimizer, loss means the loss function of training, batch_size means the mini_batch'size,
#               epochs is the maximin epochs of training,
#:param: model: GRU_CNN: num_layers


base:
    seed: 2022
    debug: False
data:
    train_len: 2
    test_len: 1
    train_dir: '/nfs/volume-807-1/houmin/hdh/15_train'
    test_dir: '/nfs/volume-807-1/houmin/hdh/15_test'
    label_index: 3
train:
    optim: 'Adam'
    loss: 'tweedie'
    batch_size: 256
    epochs: 20
    lr_init: 0.001
    lr_decay: True
    lr_decay_rate: 0.5
    lr_decay_step: 10,15
    early_stop: True
    early_stop_patience: 15
model:
    GRU_CNN:
        current: True
        num_layers: 2
        rnn_units: 128
        input_dim: 41
        output_dim: 1
        seq_len: 17
        horizon: 4
    encoder_Transformer:
        current: False
        num_layers: 2
        seq_len: 17
        input_dim: 41
        output_dim: 1
        horizon: 4
        n_header: 8
        d_model: 256
        kernel_size: 5
    Transformer:
        current: False
        num_layers: 2
        seq_len: 10
        categoical_variables: 0
        input_dim: 41
        encode_dim: 37
        output_dim: 1
        emb_dim: 1
        horizon: 1
        n_header: 8
        d_model: 128
        kernel_size: 3
        dim_feedforward: 512
    Informer:
        current: True
        current_variables: 24
        emb_dim: 6
        num_layers: 2
        seq_len: 10
        input_dim: 24
        encode_dim: 20
        output_dim: 1
        horizon: 1
        n_header: 8
        d_model: 128
        dim_feedforward: 512
    TCN:
        current: False
        seq_len: 4
        input_dim: 46
        output_dim: 1
        horizon: 4
        kernel_size: 5
        hidden_dims: [128, 128]
    TFT:
        current: True
        seq_len: 17
        static_variables: 0
        current_variables: 24
        static_embedding_vocab_sizes: 64
        categoical_variables: 0
        embedding_vocab_sizes: 0
        variables_encoder: 24
        variables_decoder: 4
        num_masked_series: 20
        lstm_hidden_dimension: 64
        lstm_layers: 1
        dropout: 0.1
        embedding_dim: 8
        attn_heads: 8
        output_dim: 1
        encode_length: 16
    logspare_transformer:
        current: True
        current_variables: 42
        emb_dim: 6
        day: True
        day_variables: 46
        day_seq_len: 49
        num_layers: 2
        seq_len: 17
        n_embd: 64
        input_dim: 46
        sub_len: 6
        output_dim: 1
        horizon: 1
        n_header: 4
        additional_params: {sparse: None, attn_pdrop: 0.2, resid_pdrop: 0.2}
        dropout: 0.3
log:
    log_step: 100
    log_dir: './'
    plot: True